#!/bin/bash
# 快速启动脚本 - 混合架构（Ray + HTTP）

set -e

echo "============================================"
echo "Serverless vLLM - 混合架构快速启动"
echo "============================================"
echo ""

# 检查 Python
if ! command -v python &> /dev/null; then
    echo "错误: 未找到 python，请先安装 Python 3.10+"
    exit 1
fi

# 检查 Ray
if ! python -c "import ray" 2>/dev/null; then
    echo "错误: 未找到 Ray，请安装: pip install 'ray[serve]'"
    exit 1
fi

echo "✅ 环境检查通过"
echo ""
echo "架构说明："
echo "  - Manager: Ray Actor (在 Ray cluster 中)"
echo "  - Router: Ray Serve Deployment (端口 8000)"
echo "  - Worker: 独立 HTTP 服务 (端口 7000+)"
echo ""
echo "请在不同的终端窗口中执行以下命令："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "终端 1 - 启动 Ray Services (Manager + Router):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "python start_ray_services.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "终端 2 - 启动 Worker 1 (需要 GPU):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "python -m src.worker.service \\"
echo "  --worker-id worker-1 \\"
echo "  --manager-url http://localhost:8000 \\"
echo "  --port 7000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "终端 3 - 启动 Worker 2 (可选):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "python -m src.worker.service \\"
echo "  --worker-id worker-2 \\"
echo "  --manager-url http://localhost:8000 \\"
echo "  --port 7001"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "使用示例:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 检查健康状态:"
echo "   curl http://localhost:8000/health"
echo ""
echo "2. 注册模型:"
echo "   curl -X POST http://localhost:8000/v1/models/register \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"alias\": \"qwen\","
echo "       \"model_name\": \"Qwen/Qwen2.5-0.5B-Instruct\","
echo "       \"max_model_len\": 4096"
echo "     }'"
echo ""
echo "3. 查看模型列表:"
echo "   curl http://localhost:8000/v1/models"
echo ""
echo "4. 查看 Worker 列表:"
echo "   curl http://localhost:8000/workers"
echo ""
echo "5. 测试推理:"
echo "   curl -X POST http://localhost:8000/v1/chat/completions \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"model\": \"qwen\","
echo "       \"messages\": [{\"role\": \"user\", \"content\": \"Hello!\"}],"
echo "       \"max_tokens\": 50"
echo "     }'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ray Dashboard:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "http://localhost:8265"
echo ""
echo "============================================"
echo "详细文档请查看: README_RAY.md"
echo "============================================"
